# Generated by Django 5.1.6 on 2025-03-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_description',
            field=models.TextField(blank=True, default='Default note', max_length=100, null=True),
        ),
    ]
