# Generated by Django 5.1.6 on 2025-06-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sCalendar', '0002_alter_note_note_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=50),
        ),
    ]
