# Generated by Django 5.1.6 on 2025-06-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sCalendar', '0003_note_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='color',
        ),
    ]
