# Generated by Django 5.1.5 on 2025-02-20 04:15

import sCalendar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='note',
            field=models.TextField(default='Default note', max_length=300, validators=[sCalendar.models.validate_nonempty]),
        ),
    ]
