# Generated by Django 5.1.5 on 2025-02-20 04:59

import sCalendar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sCalendar', '0002_event_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(default='Default note', max_length=300, validators=[sCalendar.models.validate_nonempty])),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='note',
        ),
    ]
